{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "garage-operator.fullname" . }}-allow-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garage-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "garage-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        {{- toYaml .Values.networkPolicy.allowedNamespaceSelector | nindent 8 }}
    ports:
    - port: 8443
      protocol: TCP
{{- end }}
